AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/*_spec.rb'

# Disabled cops.

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# vim: sw=2 sts=2 ts=8 et:
